// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwpP20zgH00C4uUWZDRB0x4jokNR0w48',
    appId: '1:15104468262:web:24a5830b5fa909b1c84de7',
    messagingSenderId: '15104468262',
    projectId: 'cohort-2-firebase-demo',
    authDomain: 'cohort-2-firebase-demo.firebaseapp.com',
    storageBucket: 'cohort-2-firebase-demo.appspot.com',
    measurementId: 'G-TXPGMC0C0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAccqyp2bDQCHpuCBVl8t1QgVDqfvwR9g',
    appId: '1:15104468262:android:9e090f3de99166a5c84de7',
    messagingSenderId: '15104468262',
    projectId: 'cohort-2-firebase-demo',
    storageBucket: 'cohort-2-firebase-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_4xLi-37_o56ULDCnfhszYmAh9a8Pvc',
    appId: '1:15104468262:ios:ba7467232c72e300c84de7',
    messagingSenderId: '15104468262',
    projectId: 'cohort-2-firebase-demo',
    storageBucket: 'cohort-2-firebase-demo.appspot.com',
    iosClientId: '15104468262-viecb8kfqbqk0jn5ha12kr34ei426tfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_4xLi-37_o56ULDCnfhszYmAh9a8Pvc',
    appId: '1:15104468262:ios:ba7467232c72e300c84de7',
    messagingSenderId: '15104468262',
    projectId: 'cohort-2-firebase-demo',
    storageBucket: 'cohort-2-firebase-demo.appspot.com',
    iosClientId: '15104468262-viecb8kfqbqk0jn5ha12kr34ei426tfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoChatApp',
  );
}
